name: Release
on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.RELEASE_PAT }}
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: build
        run: npm run build
      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
        run: npm run publish

  publish_on_mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.RELEASE_PAT }}
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: install additional dependency
        run: |
          python3 -m pip install setuptools
          npm install -D appdmg
      - name: build
        run: npm run build
      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
        run: npm run publish
