name: Tag Creation
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  create_tag:
    if: github.event.pull_request.merged== true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: avides/actions-project-version-check@v1.4.0
        id: actions_project_version_check
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file-to-check: package.json
          only-return-version: true
      - name: Set Version Variable
        run: echo "Version=v${{ steps.actions_project_version_check.outputs.version }}" >> $GITHUB_ENV
      - name: Create Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git tag ${{env.Version}}
      - name: Push Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin ${{env.Version}}
